services: 
  postgres: 
    image: postgres:15 
    container_name: dw_postgres 
    environment: 
      POSTGRES_DB: data_warehouse 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password 
    ports: 
      - "5432:5432" 
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
 
  pgadmin: 
    image: dpage/pgadmin4:latest 
    container_name: dw_pgadmin 
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@example.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports: 
      - "8080:80" 
 
volumes: 
  postgres_data: 
